"""add golden table

Revision ID: 11da7b4790f8
Revises: 6876a50bd48e
Create Date: 2026-05-06 11:40:45.623162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11da7b4790f8'
down_revision: Union[str, Sequence[str], None] = '6876a50bd48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refined_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processed_source_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('vectorized', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['processed_source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )

    op.add_column('source', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.add_column('source', sa.Column('simhash', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_source_content_hash'), 'source', ['content_hash'], unique=True)
    op.create_index(op.f('ix_source_simhash'), 'source', ['simhash'], unique=False)
    op.drop_column('source', 'vectorized')
    op.drop_column('source', 'summary')
    op.drop_column('source', 'topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('vectorized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_source_simhash'), table_name='source')
    op.drop_index(op.f('ix_source_content_hash'), table_name='source')
    op.drop_column('source', 'simhash')
    op.drop_column('source', 'content_hash')
    op.drop_table('refined_source')
    # ### end Alembic commands ###
