"""add title to sources

Revision ID: 53d32dcc07ab
Revises: 0d0867707a4c
Create Date: 2026-04-14 11:54:37.091084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d32dcc07ab'
down_revision: Union[str, Sequence[str], None] = '0d0867707a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'title')
    # ### end Alembic commands ###
