"""add summarization fields

Revision ID: 6876a50bd48e
Revises: e0b9ed405fac
Create Date: 2026-05-05 11:48:32.491374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6876a50bd48e'
down_revision: Union[str, Sequence[str], None] = 'e0b9ed405fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('source', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'topics')
    op.drop_column('source', 'summary')
    # ### end Alembic commands ###
