"""make title and body nullable

Revision ID: a5276d4967cb
Revises: 53d32dcc07ab
Create Date: 2026-04-14 12:50:10.284903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5276d4967cb'
down_revision: Union[str, Sequence[str], None] = '53d32dcc07ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'source', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='unique')
    op.alter_column('source', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
